/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Devuelve el estado del sistema.
         *
         *     Chequea:
         *     - App corre (200).
         *     - DB responde (SELECT 1).
         *     - Version de la API expuesta para debugging cross-env.
         *
         *     Responde 200 si todo bien, 503 si la DB no responde.
         */
        get: operations["api_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["candidatos_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos-favoritos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        get: operations["candidatos_favoritos_list"];
        put?: never;
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        post: operations["candidatos_favoritos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos-favoritos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        delete: operations["candidatos_favoritos_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos/{candidato_id}/match-detalle/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/v1/candidatos/<id>/match-detalle/ - explicacion del match del user. */
        get: operations["candidatos_match_detalle_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos/{candidato_id}/noticias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/candidatos/<candidato_id>/noticias/ - noticias que mencionan al candidato. */
        get: operations["candidatos_noticias_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos/{candidato_id}/posturas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /candidatos/<candidato_id>/posturas/.
         *
         *     Devuelve todas las posturas del candidato (12 tipicamente), con la
         *     pregunta + opcion elegida + justificacion + eje tematico expandidos.
         *
         *     Publico: cualquiera puede ver las posturas de un candidato (es data
         *     editorial, no PII del user).
         */
        get: operations["candidatos_posturas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["candidatos_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comunas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /comunas/: lista comunas para dropdown/autocomplete.
         *
         *     Query params:
         *     - `region_id`: filtra por region.
         *     - `q`: match parcial case-insensitive en nombre de comuna.
         */
        get: operations["comunas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/descartados/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        get: operations["descartados_list"];
        put?: never;
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        post: operations["descartados_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/descartados/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        delete: operations["descartados_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ejes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /ejes/: lista todos los ejes activos ordenados por `orden`.
         *
         *     Publico: se usa desde el frontend para dropdown de filtros, radar chart
         *     con colores canonicos, y tooltips educativos.
         */
        get: operations["ejes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Devuelve el estado del sistema.
         *
         *     Chequea:
         *     - App corre (200).
         *     - DB responde (SELECT 1).
         *     - Version de la API expuesta para debugging cross-env.
         *
         *     Responde 200 si todo bien, 503 si la DB no responde.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Login. Retorna token, user_id y email. */
        post: operations["login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /logout/ -> borra el token del user actual (invalidacion inmediata). */
        post: operations["logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-anonimo/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Match para usuarios guest. No persiste nada. */
        post: operations["match_anonimo_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-candidatos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Calculo de match. Usa POST porque persiste estado (no idempotente en el sentido HTTP). */
        post: operations["match_candidatos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mi-progreso/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Resumen de progreso del user en TODOS los tipos de eleccion no-base. Para cada tipo devuelve total de preguntas (incluye base), cantidad respondida y el top match si el cuestionario esta completo. */
        get: operations["mi_progreso_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/noticias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/noticias/ (feed global, con filtros opcionales) / POST admin. */
        get: operations["noticias_list"];
        put?: never;
        /** @description GET /api/noticias/ (feed global, con filtros opcionales) / POST admin. */
        post: operations["noticias_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/noticias-guardadas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["noticias_guardadas_list"];
        put?: never;
        post: operations["noticias_guardadas_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/noticias-guardadas/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["noticias_guardadas_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/noticias/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["noticias_retrieve"];
        put: operations["noticias_update"];
        post?: never;
        delete: operations["noticias_destroy"];
        options?: never;
        head?: never;
        patch: operations["noticias_partial_update"];
        trace?: never;
    };
    "/api/v1/password-reset/confirm/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /password-reset/confirm/ -> cambia password si el token es valido. */
        post: operations["password_reset_confirm_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/password-reset/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /password-reset/request/ -> genera token y envia email. */
        post: operations["password_reset_request_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfil/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET: devuelve info del user + contadores. DELETE: elimina la cuenta. */
        get: operations["perfil_retrieve"];
        put?: never;
        post?: never;
        /** @description GET: devuelve info del user + contadores. DELETE: elimina la cuenta. */
        delete: operations["perfil_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfil/cambiar-password/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description POST /perfil/cambiar-password/: cambia password verificando la actual. */
        post: operations["perfil_cambiar_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/perfil/comuna/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description PATCH /perfil/comuna/: setea o limpia la comuna donde vota el usuario.
         *
         *     Body: {"comuna_id": <int|null>}
         *     Respuesta: perfil actualizado con la comuna inline.
         */
        patch: operations["perfil_comuna_partial_update"];
        trace?: never;
    };
    "/api/v1/posturas-guardadas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["posturas_guardadas_list"];
        put?: never;
        post: operations["posturas_guardadas_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posturas-guardadas/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["posturas_guardadas_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/preguntas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Lista preguntas pendientes de responder.
         *
         *     - Autenticado: excluye las que ya respondio el user.
         *     - Guest (anonymous): devuelve todas las preguntas del tipo de eleccion.
         */
        get: operations["preguntas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regiones/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /regiones/: lista las 16 regiones ordenadas norte-sur. */
        get: operations["regiones_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/respuestas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respuestas_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/respuestas/mias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /respuestas/mias/?tipo_eleccion_id=X: lista respuestas del user auth.
         *
         *     Incluye la pregunta, el eje tematico, la opcion elegida, el peso y
         *     todas las opciones disponibles (para poblar el editor).
         */
        get: operations["respuestas_mias_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/respuestas/mias/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description PATCH /respuestas/mias/{pk}/: actualiza opcion + peso de UNA respuesta.
         *
         *     Efecto colateral: s MatchCandidato del user para el tipo
         *     de eleccion afectado (se recalculan lazy al pedir Resultados).
         */
        patch: operations["respuestas_mias_partial_update"];
        trace?: never;
    };
    "/api/v1/respuestas/reiniciar/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Borra todas las respuestas + matches del user para un tipo de eleccion.
         *
         *     NO toca favoritos, descartados ni decision final: esos son bookmarks
         *     personales aparte del cuestionario.
         */
        post: operations["respuestas_reiniciar_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tipos-eleccion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tipos_eleccion_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades-territoriales/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /unidades-territoriales/ con filtros:
         *
         *     - ?nivel=comunal  -> solo comunas
         *     - ?padre=<id>     -> solo hijos directos de esa unidad (ej. comunas del D10)
         *     - ?q=nunoa        -> busqueda por nombre (icontains)
         */
        get: operations["unidades_territoriales_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Serializer para resultados de match anonimo (guest).
         *
         *     Trabaja con el dict ScoreCandidato del service, no con un modelo.
         *     Mismo shape que MatchCandidatoResultSerializer para que el frontend
         *     pueda usar un solo tipo Result.
         */
        AnonMatchResult: {
            readonly candidato_data: {
                [key: string]: unknown;
            };
            /** Format: decimal */
            readonly match_percentage: string;
            readonly preguntas_consideradas: number;
            readonly breakdown_por_eje: {
                [key: string]: unknown;
            };
            readonly confianza: string;
        };
        AuthToken: {
            readonly token: string;
        };
        AuthTokenRequest: {
            /** Nombre de usuario */
            username: string;
            /** Contraseña */
            password: string;
        };
        CambiarPasswordRequest: {
            current_password: string;
            new_password: string;
        };
        Candidato: {
            readonly id: number;
            nombre: string;
            apellido?: string;
            /** @description Nombre del partido politico */
            partido: string;
            /** @description Breve descripción */
            bio?: string | null;
            ciudad?: string;
            /** @description Resumen o texto principal de su propuesta electoral. */
            propuesta_electoral: string;
            /** Format: uri */
            profile_picture?: string | null;
            tipos_eleccion: number[];
            readonly tipos_eleccion_nombres: string[];
            /** @description Unidad territorial polimorfica. Permite escalar a senadores (regional), CORE (provincial), etc. sin agregar FKs nuevos. */
            unidad_territorial?: number | null;
            readonly comuna_nombre: string;
            readonly comuna_region_nombre: string;
            readonly distrito_numero: string;
            readonly distrito_nombre: string;
            readonly alcance_territorial: string;
        };
        /**
         * @description Valida que no exista ya un bookmark (user, <objeto>) para este user.
         *
         *     El modelo YA tiene el `unique_together = ("user", <objeto>)`, entonces
         *     intentar guardar duplicado terminaria en IntegrityError -> HTTP 500 feo.
         *     Este mixin adelanta la validacion y devuelve un 400 con mensaje amigable.
         *
         *     Subclases declaran:
         *         unique_object_field: str        # ej. "candidato", "noticia"
         *         unique_error_message: str       # ej. "Este candidato ya esta en tus favoritos."
         */
        CandidatoDescartado: {
            readonly id: number;
            candidato: number;
            /** Format: date-time */
            readonly fecha_descartado: string;
            readonly candidato_data: components["schemas"]["Candidato"];
        };
        /**
         * @description Valida que no exista ya un bookmark (user, <objeto>) para este user.
         *
         *     El modelo YA tiene el `unique_together = ("user", <objeto>)`, entonces
         *     intentar guardar duplicado terminaria en IntegrityError -> HTTP 500 feo.
         *     Este mixin adelanta la validacion y devuelve un 400 con mensaje amigable.
         *
         *     Subclases declaran:
         *         unique_object_field: str        # ej. "candidato", "noticia"
         *         unique_error_message: str       # ej. "Este candidato ya esta en tus favoritos."
         */
        CandidatoDescartadoRequest: {
            candidato: number;
        };
        /**
         * @description Valida que no exista ya un bookmark (user, <objeto>) para este user.
         *
         *     El modelo YA tiene el `unique_together = ("user", <objeto>)`, entonces
         *     intentar guardar duplicado terminaria en IntegrityError -> HTTP 500 feo.
         *     Este mixin adelanta la validacion y devuelve un 400 con mensaje amigable.
         *
         *     Subclases declaran:
         *         unique_object_field: str        # ej. "candidato", "noticia"
         *         unique_error_message: str       # ej. "Este candidato ya esta en tus favoritos."
         */
        CandidatoFavorito: {
            readonly id: number;
            candidato: number;
            /** Format: date-time */
            readonly fecha_agregado: string;
            readonly candidato_data: components["schemas"]["Candidato"];
        };
        /**
         * @description Valida que no exista ya un bookmark (user, <objeto>) para este user.
         *
         *     El modelo YA tiene el `unique_together = ("user", <objeto>)`, entonces
         *     intentar guardar duplicado terminaria en IntegrityError -> HTTP 500 feo.
         *     Este mixin adelanta la validacion y devuelve un 400 con mensaje amigable.
         *
         *     Subclases declaran:
         *         unique_object_field: str        # ej. "candidato", "noticia"
         *         unique_error_message: str       # ej. "Este candidato ya esta en tus favoritos."
         */
        CandidatoFavoritoRequest: {
            candidato: number;
        };
        /** @description Info minima del candidato para chips en el feed de noticias. */
        CandidatoMencionado: {
            readonly id: number;
            nombre: string;
            apellido?: string;
            /** @description Nombre del partido politico */
            partido: string;
        };
        /** @description Info minima del candidato para chips en el feed de noticias. */
        CandidatoMencionadoRequest: {
            nombre: string;
            apellido?: string;
            /** @description Nombre del partido politico */
            partido: string;
        };
        CandidatoRequest: {
            nombre: string;
            apellido?: string;
            /** @description Nombre del partido politico */
            partido: string;
            /** @description Breve descripción */
            bio?: string | null;
            ciudad?: string;
            /** @description Resumen o texto principal de su propuesta electoral. */
            propuesta_electoral: string;
            /** Format: binary */
            profile_picture?: string;
            tipos_eleccion: number[];
            /** @description Unidad territorial polimorfica. Permite escalar a senadores (regional), CORE (provincial), etc. sin agregar FKs nuevos. */
            unidad_territorial?: number | null;
        };
        /** @description Representacion inline de comuna dentro del perfil. */
        ComunaInline: {
            readonly id: number;
            /** @description Codigo oficial de comuna (5 digitos SUBDERE). */
            codigo: string;
            nombre: string;
            readonly region_nombre: string;
            readonly distrito_numero: number;
        };
        /**
         * @description * `tentativa` - Tentativa (pocos datos)
         *     * `media` - Confianza media
         *     * `alta` - Confianza alta
         * @enum {string}
         */
        ConfianzaEnum: "tentativa" | "media" | "alta";
        Contadores: {
            respuestas: number;
            favoritos: number;
            descartados: number;
        };
        Eje: {
            readonly id: number;
            /** @description Slug canonico. Ej: 'ECONOMIA', 'SALUD'. Se compara case-insensitive. */
            codigo: string;
            /** @description Nombre para mostrar. Ej: 'Economia', 'Salud'. */
            nombre: string;
            /** @description Color hex para el radar chart y badges. Ej: '#FFC220'. */
            color?: string;
            /** @description Nombre de icono (Ionicons/Lucide). Opcional. */
            icono?: string;
            /**
             * Format: int64
             * @description Orden de aparicion en el radar/UI.
             */
            orden?: number;
            /** @description Si esta desactivado, el eje sigue en DB pero no se muestra al usuario. */
            activo?: boolean;
            /** @description Descripcion educativa del eje. Se muestra en tooltips. */
            descripcion?: string;
        };
        /**
         * @description * `ECONOMIA` - Economia
         *     * `SOCIEDAD` - Sociedad
         *     * `AMBIENTE` - Ambiente
         *     * `SEGURIDAD` - Seguridad
         *     * `DDHH` - Derechos Humanos
         *     * `INTERNACIONAL` - Politica Internacional
         *     * `INSTITUCIONAL` - Reforma Institucional
         *     * `OTRO` - Otro
         * @enum {string}
         */
        EjeTematicoEnum: "ECONOMIA" | "SOCIEDAD" | "AMBIENTE" | "SEGURIDAD" | "DDHH" | "INTERNACIONAL" | "INSTITUCIONAL" | "OTRO";
        MatchCandidatoResult: {
            readonly id: number;
            readonly user: string;
            readonly candidato_data: components["schemas"]["Candidato"];
            /** Format: decimal */
            readonly match_percentage: string;
            readonly preguntas_consideradas: number;
            /** @description Dict eje -> {'porcentaje': X, 'preguntas': N}. Para radar chart en el frontend. */
            breakdown_por_eje?: unknown;
            confianza?: components["schemas"]["ConfianzaEnum"];
            readonly confianza_display: string;
        };
        MatchCandidatoResultRequest: {
            /** @description Dict eje -> {'porcentaje': X, 'preguntas': N}. Para radar chart en el frontend. */
            breakdown_por_eje?: unknown;
            confianza?: components["schemas"]["ConfianzaEnum"];
        };
        /** @description Un item por tipo de eleccion no-base. */
        MiProgresoItem: {
            tipo_eleccion_id: number;
            tipo_eleccion_nombre: string;
            total_preguntas: number;
            respondidas: number;
            completa: boolean;
            top_match: components["schemas"]["MiProgresoTopMatch"] | null;
        };
        /** @description Shape reducido del top match para hero cards en el Home. */
        MiProgresoTopMatch: {
            readonly candidato: components["schemas"]["Candidato"];
            /** Format: decimal */
            readonly match_percentage: string;
            readonly preguntas_consideradas: number;
            readonly confianza: string;
            readonly confianza_display: string;
            readonly breakdown_por_eje: unknown;
        };
        /**
         * @description Respuesta del user con pregunta + eje + opciones disponibles.
         *
         *     Diseñado para el editor: el cliente muestra la pregunta, la opcion
         *     actual (con peso), y las alternativas para elegir otra.
         */
        MisRespuestasItem: {
            readonly id: number;
            readonly pregunta: number;
            readonly pregunta_texto: string;
            readonly eje_tematico: string;
            readonly eje_tematico_display: string;
            readonly opcion_elegida: number;
            /**
             * @description Cuanto le importa al usuario este tema. Multiplica el peso de la pregunta en el match.
             *
             *     * `0` - No me importa
             *     * `1` - Poco importante
             *     * `2` - Importante
             *     * `3` - Muy importante
             */
            readonly peso: components["schemas"]["PesoEnum"];
            readonly opciones: components["schemas"]["OpcionSimple"][];
            /** Format: date-time */
            readonly fecha_respuesta: string;
        };
        /**
         * @description * `nacional` - Nacional
         *     * `regional` - Regional
         *     * `provincial` - Provincial
         *     * `distrital` - Distrital
         *     * `comunal` - Comunal
         * @enum {string}
         */
        NivelEnum: "nacional" | "regional" | "provincial" | "distrital" | "comunal";
        Noticia: {
            readonly id: number;
            titulo: string;
            descripcion: string;
            /** @description Link al articulo original. Se usa como clave logica para dedup. */
            url?: string;
            /** @description Medio de origen: 'Google News', 'La Tercera', 'Emol', etc. */
            fuente?: string;
            /** @description URL del thumbnail (opcional). */
            imagen_url?: string;
            candidatos_mencionados?: number[];
            readonly candidatos_mencionados_data: components["schemas"]["CandidatoMencionado"][];
            /** Format: date-time */
            readonly fecha_publicacion: string;
            /** Format: date-time */
            readonly actualizado_en: string;
        };
        /**
         * @description Valida que no exista ya un bookmark (user, <objeto>) para este user.
         *
         *     El modelo YA tiene el `unique_together = ("user", <objeto>)`, entonces
         *     intentar guardar duplicado terminaria en IntegrityError -> HTTP 500 feo.
         *     Este mixin adelanta la validacion y devuelve un 400 con mensaje amigable.
         *
         *     Subclases declaran:
         *         unique_object_field: str        # ej. "candidato", "noticia"
         *         unique_error_message: str       # ej. "Este candidato ya esta en tus favoritos."
         */
        NoticiaBookmark: {
            readonly id: number;
            noticia: number;
            /** Format: date-time */
            readonly fecha_agregado: string;
            readonly noticia_data: components["schemas"]["Noticia"];
        };
        /**
         * @description Valida que no exista ya un bookmark (user, <objeto>) para este user.
         *
         *     El modelo YA tiene el `unique_together = ("user", <objeto>)`, entonces
         *     intentar guardar duplicado terminaria en IntegrityError -> HTTP 500 feo.
         *     Este mixin adelanta la validacion y devuelve un 400 con mensaje amigable.
         *
         *     Subclases declaran:
         *         unique_object_field: str        # ej. "candidato", "noticia"
         *         unique_error_message: str       # ej. "Este candidato ya esta en tus favoritos."
         */
        NoticiaBookmarkRequest: {
            noticia: number;
        };
        NoticiaRequest: {
            titulo: string;
            descripcion: string;
            /** @description Link al articulo original. Se usa como clave logica para dedup. */
            url?: string;
            /** @description Medio de origen: 'Google News', 'La Tercera', 'Emol', etc. */
            fuente?: string;
            /** @description URL del thumbnail (opcional). */
            imagen_url?: string;
            candidatos_mencionados?: number[];
        };
        OpcionRespuesta: {
            readonly id: number;
            texto: string;
            /**
             * Format: int64
             * @description Valor numérico de la opción (ej. 1 al 5 para escalas, 0/1 para sí/no).
             */
            valor: number;
            /** @description Si es True, esta opcion representa 'No se / Prefiero no responder' y se excluye del calculo de match. */
            es_no_se?: boolean;
        };
        /** @description Opcion minima para poblar el editor de respuestas. */
        OpcionSimple: {
            readonly id: number;
            texto: string;
            /**
             * Format: int64
             * @description Valor numérico de la opción (ej. 1 al 5 para escalas, 0/1 para sí/no).
             */
            valor: number;
        };
        PaginatedNoticiaList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Noticia"][];
        };
        /** @description Payload: token + password nueva. */
        PasswordResetConfirmRequest: {
            token: string;
            new_password: string;
        };
        /** @description Payload: solo email. */
        PasswordResetRequestRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Body del PATCH /perfil/comuna/. Solo requiere comuna_id. */
        PatchedActualizarComunaRequest: {
            /** @description ID de la comuna donde vota. null para limpiar. */
            comuna_id?: number | null;
        };
        /** @description Input para PATCH /respuestas/mias/{id}/. */
        PatchedEditarRespuestaRequest: {
            opcion_elegida?: number;
            peso?: number;
        };
        PatchedNoticiaRequest: {
            titulo?: string;
            descripcion?: string;
            /** @description Link al articulo original. Se usa como clave logica para dedup. */
            url?: string;
            /** @description Medio de origen: 'Google News', 'La Tercera', 'Emol', etc. */
            fuente?: string;
            /** @description URL del thumbnail (opcional). */
            imagen_url?: string;
            candidatos_mencionados?: number[];
        };
        Perfil: {
            id: number;
            username: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            fecha_registro: string;
            contadores: components["schemas"]["Contadores"];
            comuna: components["schemas"]["ComunaInline"] | null;
        };
        /**
         * @description * `0` - No me importa
         *     * `1` - Poco importante
         *     * `2` - Importante
         *     * `3` - Muy importante
         * @enum {integer}
         */
        PesoEnum: 0 | 1 | 2 | 3;
        /**
         * @description Valida que no exista ya un bookmark (user, <objeto>) para este user.
         *
         *     El modelo YA tiene el `unique_together = ("user", <objeto>)`, entonces
         *     intentar guardar duplicado terminaria en IntegrityError -> HTTP 500 feo.
         *     Este mixin adelanta la validacion y devuelve un 400 con mensaje amigable.
         *
         *     Subclases declaran:
         *         unique_object_field: str        # ej. "candidato", "noticia"
         *         unique_error_message: str       # ej. "Este candidato ya esta en tus favoritos."
         */
        PosturaBookmark: {
            readonly id: number;
            postura: number;
            /** Format: date-time */
            readonly fecha_agregado: string;
            readonly postura_data: components["schemas"]["PosturaCandidato"];
        };
        /**
         * @description Valida que no exista ya un bookmark (user, <objeto>) para este user.
         *
         *     El modelo YA tiene el `unique_together = ("user", <objeto>)`, entonces
         *     intentar guardar duplicado terminaria en IntegrityError -> HTTP 500 feo.
         *     Este mixin adelanta la validacion y devuelve un 400 con mensaje amigable.
         *
         *     Subclases declaran:
         *         unique_object_field: str        # ej. "candidato", "noticia"
         *         unique_error_message: str       # ej. "Este candidato ya esta en tus favoritos."
         */
        PosturaBookmarkRequest: {
            postura: number;
        };
        PosturaCandidato: {
            readonly id: number;
            candidato: number;
            pregunta: number;
            opcion_respuesta: number;
            /** @description Breve justificación de la postura del candidato sobre el tema. */
            justificacion?: string | null;
            readonly opcion_respuesta_texto: string;
            readonly opcion_respuesta_valor: number;
            readonly candidato_nombre_completo: string;
            readonly pregunta_texto: string;
            readonly pregunta_orden: number;
            readonly eje_tematico: string;
            readonly eje_tematico_display: string;
        };
        PosturaCandidatoRequest: {
            candidato: number;
            pregunta: number;
            opcion_respuesta: number;
            /** @description Breve justificación de la postura del candidato sobre el tema. */
            justificacion?: string | null;
        };
        Pregunta: {
            readonly id: number;
            texto: string;
            /** Format: int64 */
            orden?: number;
            tipo_eleccion: number;
            readonly tipo_eleccion_nombre: string;
            /**
             * @description Categoria tematica de la pregunta. Sirve para el match por eje.
             *
             *     * `ECONOMIA` - Economia
             *     * `SOCIEDAD` - Sociedad
             *     * `AMBIENTE` - Ambiente
             *     * `SEGURIDAD` - Seguridad
             *     * `DDHH` - Derechos Humanos
             *     * `INTERNACIONAL` - Politica Internacional
             *     * `INSTITUCIONAL` - Reforma Institucional
             *     * `OTRO` - Otro
             */
            eje_tematico?: components["schemas"]["EjeTematicoEnum"];
            readonly eje_tematico_display: string;
            /** @description Referencia al catalogo Eje. Se sincroniza automaticamente con eje_tematico. Setealo aca si querés override o dejalo vacio y el signal lo resuelve por codigo. */
            eje?: number | null;
            readonly eje_nombre: string;
            readonly eje_color: string;
            readonly eje_icono: string;
            /** @description Contexto educativo neutro sobre que trata la pregunta (2-3 lineas). */
            explicacion?: string;
            /** @description Dict con keys: economico, social, cultural, ambiental, institucional. Cada valor es un texto breve explicando el impacto en esa dimension. */
            repercusiones?: unknown;
            readonly opciones_respuesta: components["schemas"]["OpcionRespuesta"][];
        };
        RespuestaUsuarioCreateRequest: {
            pregunta: number;
            opcion_elegida: number;
            /** @default 1 */
            peso: number;
        };
        TipoEleccion: {
            readonly id: number;
            /** @description Ej: Presidencial, Parlamentaria , Regional, Municipal */
            nombre: string;
            /** @description Descripciòn breve del tipo de eleccion */
            descripcion?: string | null;
            /**
             * Format: date
             * @description Fecha oficial de la eleccion
             */
            fecha_eleccion?: string | null;
            /**
             * Format: int64
             * @description Ano electoral (ej. 2021, 2025). Permite tener multiples versiones del mismo tipo (Presidencial 2021 vs Presidencial 2025) y filtrar.
             */
            anio?: number | null;
            /** @description Si es True, las preguntas de este tipo se agregan a TODAS las elecciones. Usado para preguntas transversales de valores/ideologia que se responden una sola vez. */
            es_base?: boolean;
        };
        UnidadTerritorial: {
            readonly id: number;
            /** @description Codigo canonico. Ej: 'NACIONAL', 'REG-13', 'D-10', 'COM-13120'. */
            codigo: string;
            nombre: string;
            nivel: components["schemas"]["NivelEnum"];
            /** @description Unidad de nivel superior. Ej: comuna -> distrito, distrito -> region. */
            padre?: number | null;
            readonly padre_nombre: string;
            readonly padre_nivel: string;
            /** @description Data extra: 'poblacion', 'codigo_ine', 'circunscripcion_senatorial', etc. */
            metadata?: unknown;
        };
        User: {
            readonly id: number;
            /**
             * Nombre de usuario
             * @description Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
             */
            username: string;
            /** Dirección de correo electrónico */
            email?: string;
        };
        UserRequest: {
            /**
             * Nombre de usuario
             * @description Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
             */
            username: string;
            /** Dirección de correo electrónico */
            email?: string;
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sistema OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB caida u otro fallo */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    candidatos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidato"][];
                };
            };
        };
    };
    candidatos_favoritos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatoFavorito"][];
                };
            };
        };
    };
    candidatos_favoritos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidatoFavoritoRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CandidatoFavoritoRequest"];
                "multipart/form-data": components["schemas"]["CandidatoFavoritoRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatoFavorito"];
                };
            };
        };
    };
    candidatos_favoritos_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este candidato favorito. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    candidatos_match_detalle_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidato_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    candidatos_noticias_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidato_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"][];
                };
            };
        };
    };
    candidatos_posturas_list: {
        parameters: {
            query?: {
                /** @description Filtra posturas por preguntas de este tipo de eleccion. */
                tipo_eleccion_id?: number;
            };
            header?: never;
            path: {
                candidato_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosturaCandidato"][];
                };
            };
        };
    };
    candidatos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidato"];
                };
            };
        };
    };
    comunas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunaInline"][];
                };
            };
        };
    };
    descartados_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatoDescartado"][];
                };
            };
        };
    };
    descartados_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidatoDescartadoRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CandidatoDescartadoRequest"];
                "multipart/form-data": components["schemas"]["CandidatoDescartadoRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatoDescartado"];
                };
            };
        };
    };
    descartados_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este candidato descartado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ejes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Eje"][];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sistema OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB caida u otro fallo */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AuthTokenRequest"];
                "multipart/form-data": components["schemas"]["AuthTokenRequest"];
                "application/json": components["schemas"]["AuthTokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
        };
    };
    logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesion cerrada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    match_anonimo_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                type: {
                    [key: string]: unknown;
                };
                properties: unknown;
                required: {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnonMatchResult"][];
                };
            };
            /** @description Payload invalido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    match_candidatos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MatchCandidatoResultRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MatchCandidatoResultRequest"];
                "multipart/form-data": components["schemas"]["MatchCandidatoResultRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchCandidatoResult"];
                };
            };
        };
    };
    mi_progreso_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MiProgresoItem"][];
                };
            };
            /** @description Autenticacion requerida */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    noticias_list: {
        parameters: {
            query?: {
                /** @description Filtra noticias que mencionen a este candidato. */
                candidato_id?: number;
                /** @description Solo noticias de los ultimos N dias (ej. 7, 30, 90). */
                dias?: number;
                /** @description Filtra por medio de origen (match parcial, case-insensitive). */
                fuente?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
                /** @description Busqueda de texto libre en titulo y descripcion. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNoticiaList"];
                };
            };
        };
    };
    noticias_create: {
        parameters: {
            query?: {
                /** @description Filtra noticias que mencionen a este candidato. */
                candidato_id?: number;
                /** @description Solo noticias de los ultimos N dias (ej. 7, 30, 90). */
                dias?: number;
                /** @description Filtra por medio de origen (match parcial, case-insensitive). */
                fuente?: string;
                /** @description Un número de página dentro del conjunto de resultados paginado. */
                page?: number;
                /** @description Número de resultados a devolver por página. */
                page_size?: number;
                /** @description Busqueda de texto libre en titulo y descripcion. */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticiaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NoticiaRequest"];
                "multipart/form-data": components["schemas"]["NoticiaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedNoticiaList"];
                };
            };
        };
    };
    noticias_guardadas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticiaBookmark"][];
                };
            };
        };
    };
    noticias_guardadas_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticiaBookmarkRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NoticiaBookmarkRequest"];
                "multipart/form-data": components["schemas"]["NoticiaBookmarkRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoticiaBookmark"];
                };
            };
        };
    };
    noticias_guardadas_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este noticia bookmark. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    noticias_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"];
                };
            };
        };
    };
    noticias_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticiaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NoticiaRequest"];
                "multipart/form-data": components["schemas"]["NoticiaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"];
                };
            };
        };
    };
    noticias_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    noticias_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNoticiaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNoticiaRequest"];
                "multipart/form-data": components["schemas"]["PatchedNoticiaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"];
                };
            };
        };
    };
    password_reset_confirm_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirmRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Password cambiada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Token invalido / expirado / password debil */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    password_reset_request_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequestRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequestRequest"];
            };
        };
        responses: {
            /** @description email_sent siempre True (no revelamos si el email existe). En DEBUG=True devuelve reset_link para testing. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    perfil_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
        };
    };
    perfil_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuenta eliminada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Password incorrecta o faltante */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    perfil_cambiar_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambiarPasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CambiarPasswordRequest"];
                "multipart/form-data": components["schemas"]["CambiarPasswordRequest"];
            };
        };
        responses: {
            /** @description Password actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Password actual incorrecta o nueva invalida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    perfil_comuna_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedActualizarComunaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedActualizarComunaRequest"];
                "multipart/form-data": components["schemas"]["PatchedActualizarComunaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComunaInline"];
                };
            };
            /** @description comuna_id invalido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    posturas_guardadas_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosturaBookmark"][];
                };
            };
        };
    };
    posturas_guardadas_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PosturaBookmarkRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PosturaBookmarkRequest"];
                "multipart/form-data": components["schemas"]["PosturaBookmarkRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PosturaBookmark"];
                };
            };
        };
    };
    posturas_guardadas_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este postura bookmark. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    preguntas_list: {
        parameters: {
            query: {
                tipo_eleccion_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pregunta"][];
                };
            };
            /** @description tipo_eleccion_id faltante */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    regiones_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    respuestas_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespuestaUsuarioCreateRequest"][];
                "application/x-www-form-urlencoded": components["schemas"]["RespuestaUsuarioCreateRequest"][];
                "multipart/form-data": components["schemas"]["RespuestaUsuarioCreateRequest"][];
            };
        };
        responses: {
            /** @description Respuestas guardadas OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payload invalido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    respuestas_mias_list: {
        parameters: {
            query: {
                tipo_eleccion_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MisRespuestasItem"][];
                };
            };
            /** @description tipo_eleccion_id faltante */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    respuestas_mias_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedEditarRespuestaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedEditarRespuestaRequest"];
                "multipart/form-data": components["schemas"]["PatchedEditarRespuestaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MisRespuestasItem"];
                };
            };
            /** @description Payload invalido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Respuesta no encontrada */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    respuestas_reiniciar_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    tipo_eleccion_id: number;
                };
            };
        };
        responses: {
            /** @description Cuestionario reiniciado. Devuelve counts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description tipo_eleccion_id faltante */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Tipo de eleccion no encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tipos_eleccion_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoEleccion"][];
                };
            };
        };
    };
    unidades_territoriales_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnidadTerritorial"][];
                };
            };
        };
    };
}
