/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Devuelve el estado del sistema.
         *
         *     Chequea:
         *     - App corre (200).
         *     - DB responde (SELECT 1).
         *     - Version de la API expuesta para debugging cross-env.
         *
         *     Responde 200 si todo bien, 503 si la DB no responde.
         */
        get: operations["api_health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["candidatos_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos-favoritos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        get: operations["candidatos_favoritos_list"];
        put?: never;
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        post: operations["candidatos_favoritos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos-favoritos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        delete: operations["candidatos_favoritos_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos/{candidato_id}/noticias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description GET /api/candidatos/<candidato_id>/noticias/ - noticias que mencionan al candidato. */
        get: operations["candidatos_noticias_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/candidatos/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["candidatos_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-final/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Voto final del usuario por tipo de eleccion. */
        get: operations["decision_final_list"];
        put?: never;
        /** @description Voto final del usuario por tipo de eleccion. */
        post: operations["decision_final_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decision-final/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Voto final del usuario por tipo de eleccion. */
        get: operations["decision_final_retrieve"];
        put?: never;
        post?: never;
        /** @description Voto final del usuario por tipo de eleccion. */
        delete: operations["decision_final_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/descartados/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        get: operations["descartados_list"];
        put?: never;
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        post: operations["descartados_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/descartados/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Base para viewsets que solo listan/crean/borran items del user actual. */
        delete: operations["descartados_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Login. Retorna token, user_id y email. */
        post: operations["login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/match-candidatos/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Calculo de match. Usa POST porque persiste estado (no idempotente en el sentido HTTP). */
        post: operations["match_candidatos_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/noticias/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["noticias_list"];
        put?: never;
        post: operations["noticias_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/noticias/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["noticias_retrieve"];
        put: operations["noticias_update"];
        post?: never;
        delete: operations["noticias_destroy"];
        options?: never;
        head?: never;
        patch: operations["noticias_partial_update"];
        trace?: never;
    };
    "/api/v1/preguntas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["preguntas_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/respuestas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["respuestas_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tipos-eleccion/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tipos_eleccion_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthToken: {
            readonly token: string;
        };
        AuthTokenRequest: {
            /** Nombre de usuario */
            username: string;
            /** Contraseña */
            password: string;
        };
        Candidato: {
            readonly id: number;
            nombre: string;
            apellido?: string;
            /** @description Nombre del partido politico */
            partido: string;
            /** @description Breve descripción */
            bio?: string | null;
            ciudad?: string;
            /** @description Resumen o texto principal de su propuesta electoral. */
            propuesta_electoral: string;
            /** Format: uri */
            profile_picture?: string | null;
            tipos_eleccion: number[];
            readonly tipos_eleccion_nombres: string[];
        };
        CandidatoDescartado: {
            readonly id: number;
            candidato: number;
            /** Format: date-time */
            readonly fecha_descartado: string;
            readonly candidato_data: components["schemas"]["Candidato"];
        };
        CandidatoDescartadoRequest: {
            candidato: number;
        };
        CandidatoFavorito: {
            readonly id: number;
            candidato: number;
            /** Format: date-time */
            readonly fecha_agregado: string;
            readonly candidato_data: components["schemas"]["Candidato"];
        };
        CandidatoFavoritoRequest: {
            candidato: number;
        };
        CandidatoRequest: {
            nombre: string;
            apellido?: string;
            /** @description Nombre del partido politico */
            partido: string;
            /** @description Breve descripción */
            bio?: string | null;
            ciudad?: string;
            /** @description Resumen o texto principal de su propuesta electoral. */
            propuesta_electoral: string;
            /** Format: binary */
            profile_picture?: string;
            tipos_eleccion: number[];
        };
        /**
         * @description * `tentativa` - Tentativa (pocos datos)
         *     * `media` - Confianza media
         *     * `alta` - Confianza alta
         * @enum {string}
         */
        ConfianzaEnum: "tentativa" | "media" | "alta";
        DecisionFinal: {
            readonly id: number;
            candidato_elegido: number;
            tipo_eleccion: number;
            /** Format: date-time */
            readonly fecha_decision: string;
            readonly candidato_data: components["schemas"]["Candidato"];
            readonly tipo_eleccion_nombre: string;
        };
        DecisionFinalRequest: {
            candidato_elegido: number;
            tipo_eleccion: number;
        };
        /**
         * @description * `ECONOMIA` - Economia
         *     * `SOCIEDAD` - Sociedad
         *     * `AMBIENTE` - Ambiente
         *     * `SEGURIDAD` - Seguridad
         *     * `DDHH` - Derechos Humanos
         *     * `INTERNACIONAL` - Politica Internacional
         *     * `INSTITUCIONAL` - Reforma Institucional
         *     * `OTRO` - Otro
         * @enum {string}
         */
        EjeTematicoEnum: "ECONOMIA" | "SOCIEDAD" | "AMBIENTE" | "SEGURIDAD" | "DDHH" | "INTERNACIONAL" | "INSTITUCIONAL" | "OTRO";
        MatchCandidatoResult: {
            readonly id: number;
            readonly user: string;
            readonly candidato_data: components["schemas"]["Candidato"];
            /** Format: decimal */
            readonly match_percentage: string;
            readonly preguntas_consideradas: number;
            /** @description Dict eje -> {'porcentaje': X, 'preguntas': N}. Para radar chart en el frontend. */
            breakdown_por_eje?: unknown;
            confianza?: components["schemas"]["ConfianzaEnum"];
            readonly confianza_display: string;
        };
        MatchCandidatoResultRequest: {
            /** @description Dict eje -> {'porcentaje': X, 'preguntas': N}. Para radar chart en el frontend. */
            breakdown_por_eje?: unknown;
            confianza?: components["schemas"]["ConfianzaEnum"];
        };
        Noticia: {
            readonly id: number;
            titulo: string;
            descripcion: string;
            /** @description Link al articulo original. Se usa como clave logica para dedup. */
            url?: string;
            /** @description Medio de origen: 'Google News', 'La Tercera', 'Emol', etc. */
            fuente?: string;
            /** @description URL del thumbnail (opcional). */
            imagen_url?: string;
            candidatos_mencionados?: number[];
            /** Format: date-time */
            readonly fecha_publicacion: string;
            /** Format: date-time */
            readonly actualizado_en: string;
        };
        NoticiaRequest: {
            titulo: string;
            descripcion: string;
            /** @description Link al articulo original. Se usa como clave logica para dedup. */
            url?: string;
            /** @description Medio de origen: 'Google News', 'La Tercera', 'Emol', etc. */
            fuente?: string;
            /** @description URL del thumbnail (opcional). */
            imagen_url?: string;
            candidatos_mencionados?: number[];
        };
        OpcionRespuesta: {
            readonly id: number;
            texto: string;
            /**
             * Format: int64
             * @description Valor numérico de la opción (ej. 1 al 5 para escalas, 0/1 para sí/no).
             */
            valor: number;
            /** @description Si es True, esta opcion representa 'No se / Prefiero no responder' y se excluye del calculo de match. */
            es_no_se?: boolean;
        };
        PatchedNoticiaRequest: {
            titulo?: string;
            descripcion?: string;
            /** @description Link al articulo original. Se usa como clave logica para dedup. */
            url?: string;
            /** @description Medio de origen: 'Google News', 'La Tercera', 'Emol', etc. */
            fuente?: string;
            /** @description URL del thumbnail (opcional). */
            imagen_url?: string;
            candidatos_mencionados?: number[];
        };
        Pregunta: {
            readonly id: number;
            texto: string;
            /** Format: int64 */
            orden?: number;
            tipo_eleccion: number;
            readonly tipo_eleccion_nombre: string;
            /**
             * @description Categoria tematica de la pregunta. Sirve para el match por eje.
             *
             *     * `ECONOMIA` - Economia
             *     * `SOCIEDAD` - Sociedad
             *     * `AMBIENTE` - Ambiente
             *     * `SEGURIDAD` - Seguridad
             *     * `DDHH` - Derechos Humanos
             *     * `INTERNACIONAL` - Politica Internacional
             *     * `INSTITUCIONAL` - Reforma Institucional
             *     * `OTRO` - Otro
             */
            eje_tematico?: components["schemas"]["EjeTematicoEnum"];
            readonly eje_tematico_display: string;
            /** @description Contexto educativo neutro sobre que trata la pregunta (2-3 lineas). */
            explicacion?: string;
            /** @description Dict con keys: economico, social, cultural, ambiental, institucional. Cada valor es un texto breve explicando el impacto en esa dimension. */
            repercusiones?: unknown;
            readonly opciones_respuesta: components["schemas"]["OpcionRespuesta"][];
        };
        RespuestaUsuarioCreateRequest: {
            pregunta: number;
            opcion_elegida: number;
            /** @default 1 */
            peso: number;
        };
        TipoEleccion: {
            readonly id: number;
            /** @description Ej: Presidencial, Parlamentaria , Regional, Municipal */
            nombre: string;
            /** @description Descripciòn breve del tipo de eleccion */
            descripcion?: string | null;
            /**
             * Format: date
             * @description Fecha oficial de la eleccion
             */
            fecha_eleccion?: string | null;
        };
        User: {
            readonly id: number;
            /**
             * Nombre de usuario
             * @description Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
             */
            username: string;
            /** Dirección de correo electrónico */
            email?: string;
        };
        UserRequest: {
            /**
             * Nombre de usuario
             * @description Requerido. 150 carácteres como máximo. Únicamente letras, dígitos y @/./+/-/_
             */
            username: string;
            /** Dirección de correo electrónico */
            email?: string;
            password: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sistema OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DB caida u otro fallo */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    candidatos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidato"][];
                };
            };
        };
    };
    candidatos_favoritos_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatoFavorito"][];
                };
            };
        };
    };
    candidatos_favoritos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidatoFavoritoRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CandidatoFavoritoRequest"];
                "multipart/form-data": components["schemas"]["CandidatoFavoritoRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatoFavorito"];
                };
            };
        };
    };
    candidatos_favoritos_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este candidato favorito. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    candidatos_noticias_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidato_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"][];
                };
            };
        };
    };
    candidatos_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidato"];
                };
            };
        };
    };
    decision_final_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionFinal"][];
                };
            };
        };
    };
    decision_final_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionFinalRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DecisionFinalRequest"];
                "multipart/form-data": components["schemas"]["DecisionFinalRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionFinal"];
                };
            };
        };
    };
    decision_final_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este decision final. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionFinal"];
                };
            };
        };
    };
    decision_final_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este decision final. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    descartados_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatoDescartado"][];
                };
            };
        };
    };
    descartados_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidatoDescartadoRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["CandidatoDescartadoRequest"];
                "multipart/form-data": components["schemas"]["CandidatoDescartadoRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatoDescartado"];
                };
            };
        };
    };
    descartados_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Un valor de entero único que identifique este candidato descartado. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["AuthTokenRequest"];
                "multipart/form-data": components["schemas"]["AuthTokenRequest"];
                "application/json": components["schemas"]["AuthTokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthToken"];
                };
            };
        };
    };
    match_candidatos_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MatchCandidatoResultRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MatchCandidatoResultRequest"];
                "multipart/form-data": components["schemas"]["MatchCandidatoResultRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchCandidatoResult"];
                };
            };
        };
    };
    noticias_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"][];
                };
            };
        };
    };
    noticias_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticiaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NoticiaRequest"];
                "multipart/form-data": components["schemas"]["NoticiaRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"];
                };
            };
        };
    };
    noticias_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"];
                };
            };
        };
    };
    noticias_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoticiaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["NoticiaRequest"];
                "multipart/form-data": components["schemas"]["NoticiaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"];
                };
            };
        };
    };
    noticias_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    noticias_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedNoticiaRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedNoticiaRequest"];
                "multipart/form-data": components["schemas"]["PatchedNoticiaRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Noticia"];
                };
            };
        };
    };
    preguntas_list: {
        parameters: {
            query: {
                tipo_eleccion_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pregunta"][];
                };
            };
            /** @description tipo_eleccion_id faltante */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    respuestas_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RespuestaUsuarioCreateRequest"][];
                "application/x-www-form-urlencoded": components["schemas"]["RespuestaUsuarioCreateRequest"][];
                "multipart/form-data": components["schemas"]["RespuestaUsuarioCreateRequest"][];
            };
        };
        responses: {
            /** @description Respuestas guardadas OK */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Payload invalido */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    tipos_eleccion_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TipoEleccion"][];
                };
            };
        };
    };
}
