# Generated by Django 5.2.16 on 2026-07-27 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('core', '0001_initial'), ('core', '0002_profile_perfile_picture'), ('core', '0003_alter_profile_perfile_picture'), ('core', '0004_apoyo_cualidad_interespolitico_and_more'), ('core', '0005_rename_nombre_apoyo_apoya_and_more'), ('core', '0006_match'), ('core', '0007_profile_user'), ('core', '0008_alter_profile_user'), ('core', '0009_alter_profile_user'), ('core', '0010_alter_profile_user'), ('core', '0011_alter_profile_apellido_alter_profile_bio_and_more'), ('core', '0012_candidato_opcionrespuesta_pregunta_tipoeleccion_and_more'), ('core', '0013_respuestausuario'), ('core', '0014_alter_opcionrespuesta_unique_together'), ('core', '0015_matchcandidato'), ('core', '0016_alter_posturacandidato_candidato_and_more'), ('core', '0017_alter_noticia_options_and_more'), ('core', '0018_noticia_actualizado_en'), ('core', '0019_rename_profile_picture_and_drop_noticia_unique'), ('core', '0020_algoritmo_robusto'), ('core', '0021_noticia_extendida'), ('core', '0022_pregunta_explicacion_pregunta_repercusiones'), ('core', '0023_passwordresettoken'), ('core', '0024_noticiabookmark_posturabookmark'), ('core', '0025_tipoeleccion_es_base')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, default='', max_length=100)),
                ('partido', models.CharField(help_text='Nombre del partido politico', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Breve descripción', null=True)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('propuesta_electoral', models.TextField(help_text='Resumen o texto principal de su propuesta electoral.')),
                ('perfile_picture', models.ImageField(default='assets/default.avif', upload_to='profiles/')),
            ],
            options={
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='TipoEleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Presidencial, Parlamentaria , Regional, Municipal', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripciòn breve del tipo de eleccion', null=True)),
                ('fecha_eleccion', models.DateField(blank=True, help_text='Fecha oficial de la eleccion', null=True)),
                ('es_base', models.BooleanField(default=False, help_text='Si es True, las preguntas de este tipo se agregan a TODAS las elecciones. Usado para preguntas transversales de valores/ideologia que se responden una sola vez.')),
            ],
            options={
                'verbose_name_plural': 'Tipos de elección',
            },
        ),
        migrations.CreateModel(
            name='CandidatoDescartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descartado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descartados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Candidatos Descartados',
                'unique_together': {('user', 'candidato')},
            },
        ),
        migrations.CreateModel(
            name='CandidatoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Candidatos Favoritos',
                'unique_together': {('user', 'candidato')},
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('tipo_eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.tipoeleccion')),
                ('eje_tematico', models.CharField(choices=[('ECONOMIA', 'Economia'), ('SOCIEDAD', 'Sociedad'), ('AMBIENTE', 'Ambiente'), ('SEGURIDAD', 'Seguridad'), ('DDHH', 'Derechos Humanos'), ('INTERNACIONAL', 'Politica Internacional'), ('INSTITUCIONAL', 'Reforma Institucional'), ('OTRO', 'Otro')], default='OTRO', help_text='Categoria tematica de la pregunta. Sirve para el match por eje.', max_length=20)),
                ('explicacion', models.TextField(blank=True, default='', help_text='Contexto educativo neutro sobre que trata la pregunta (2-3 lineas).')),
                ('repercusiones', models.JSONField(blank=True, default=dict, help_text='Dict con keys: economico, social, cultural, ambiental, institucional. Cada valor es un texto breve explicando el impacto en esa dimension.')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='DecisionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_decision', models.DateTimeField(auto_now_add=True)),
                ('candidato_elegido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elegido_por_usuarios', to='core.candidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones_finales', to=settings.AUTH_USER_MODEL)),
                ('tipo_eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoeleccion')),
            ],
            options={
                'verbose_name_plural': 'Decisiones Finales',
                'unique_together': {('user', 'tipo_eleccion')},
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipos_eleccion',
            field=models.ManyToManyField(related_name='candidatos', to='core.tipoeleccion'),
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('valor', models.IntegerField(help_text='Valor numérico de la opción (ej. 1 al 5 para escalas, 0/1 para sí/no).')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_respuesta', to='core.pregunta')),
                ('es_no_se', models.BooleanField(default=False, help_text="Si es True, esta opcion representa 'No se / Prefiero no responder' y se excluye del calculo de match.")),
            ],
            options={
                'verbose_name_plural': 'Opciones de respuesta',
                'unique_together': {('pregunta', 'texto')},
            },
        ),
        migrations.CreateModel(
            name='PosturaCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField(blank=True, help_text='Breve justificación de la postura del candidato sobre el tema.', null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posturas_candidato', to='core.candidato')),
                ('opcion_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
            ],
            options={
                'verbose_name_plural': 'Posturas de Candidatos',
                'unique_together': {('candidato', 'pregunta')},
            },
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='perfile_picture',
            new_name='profile_picture',
        ),
        migrations.CreateModel(
            name='MatchCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('num_preguntas_consideradas', models.IntegerField(default=0)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_candidato', to=settings.AUTH_USER_MODEL)),
                ('breakdown_por_eje', models.JSONField(blank=True, default=dict, help_text="Dict eje -> {'porcentaje': X, 'preguntas': N}. Para radar chart en el frontend.")),
                ('confianza', models.CharField(choices=[('tentativa', 'Tentativa (pocos datos)'), ('media', 'Confianza media'), ('alta', 'Confianza alta')], default='tentativa', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Matches de Candidatos',
                'unique_together': {('user', 'candidato')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('opcion_elegida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_usuario', to=settings.AUTH_USER_MODEL)),
                ('peso', models.IntegerField(choices=[(0, 'No me importa'), (1, 'Poco importante'), (2, 'Importante'), (3, 'Muy importante')], default=1, help_text='Cuanto le importa al usuario este tema. Multiplica el peso de la pregunta en el match.')),
            ],
            options={
                'verbose_name_plural': 'Respuestas de Usuarios',
                'unique_together': {('user', 'pregunta')},
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('candidatos_mencionados', models.ManyToManyField(blank=True, help_text='Candidatos referenciados por esta noticia.', related_name='noticias', to='core.candidato')),
                ('fuente', models.CharField(blank=True, default='', help_text="Medio de origen: 'Google News', 'La Tercera', 'Emol', etc.", max_length=200)),
                ('imagen_url', models.URLField(blank=True, default='', help_text='URL del thumbnail (opcional).', max_length=1000)),
                ('url', models.URLField(blank=True, default='', help_text='Link al articulo original. Se usa como clave logica para dedup.', max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'unique_together': set(),
                'ordering': ['-fecha_publicacion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('url',), name='noticia_url_unique_when_not_empty')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Password Reset Tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Noticias guardadas',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('user', 'noticia')},
            },
        ),
        migrations.CreateModel(
            name='PosturaBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('postura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.posturacandidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posturas_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posturas guardadas',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('user', 'postura')},
            },
        ),
    ]
