# Generated by Django 5.2.1 on 2025-05-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_perfile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='perfile_picture',
            field=models.ImageField(default='assets/default.avif', upload_to='profiles/'),
        ),
    ]
