# Generated by Django 5.2.1 on 2025-05-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_perfile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteresPolitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ciudad',
            field=models.CharField(default='Valparaiso', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='propuesta',
            field=models.TextField(default='No se'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='apoyos',
            field=models.ManyToManyField(blank=True, to='core.apoyo'),
        ),
        migrations.AddField(
            model_name='profile',
            name='cualidades',
            field=models.ManyToManyField(blank=True, to='core.cualidad'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interesPolitico',
            field=models.ManyToManyField(blank=True, to='core.interespolitico'),
        ),
    ]
