# Generated by Django 5.2.1 on 2025-05-22 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apoyo_cualidad_interespolitico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apoyo',
            old_name='nombre',
            new_name='apoya',
        ),
        migrations.RenameField(
            model_name='cualidad',
            old_name='nombre',
            new_name='cualidad',
        ),
        migrations.RenameField(
            model_name='interespolitico',
            old_name='nombre',
            new_name='interes',
        ),
    ]
