# Generated by Django 5.2.1 on 2025-05-31 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_profile_apellido_alter_profile_bio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, default='', max_length=100)),
                ('partido', models.CharField(help_text='Nombre del partido politico', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Breve descripción', null=True)),
                ('ciudad', models.CharField(blank=True, default='', max_length=100)),
                ('propuesta_electoral', models.TextField(help_text='Resumen o texto principal de su propuesta electoral.')),
                ('perfile_picture', models.ImageField(default='assets/default.avif', upload_to='profiles/')),
            ],
            options={
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('valor', models.IntegerField(help_text='Valor numérico de la opción (ej. 1 al 5 para escalas, 0/1 para sí/no).')),
            ],
            options={
                'verbose_name_plural': 'Opciones de respuesta',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TipoEleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Presidencial, Parlamentaria , Regional, Municipal', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripciòn breve del tipo de eleccion', null=True)),
                ('fecha_eleccion', models.DateField(blank=True, help_text='Fecha oficial de la eleccion', null=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de elección',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apoyos',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cualidades',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interesPolitico',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='match',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='match',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.CreateModel(
            name='CandidatoDescartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_descartado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descartados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Candidatos Descartados',
                'unique_together': {('user', 'candidato')},
            },
        ),
        migrations.CreateModel(
            name='CandidatoFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Candidatos Favoritos',
                'unique_together': {('user', 'candidato')},
            },
        ),
        migrations.CreateModel(
            name='PosturaCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificacion', models.TextField(blank=True, help_text='Breve justificación de la postura del candidato sobre el tema.', null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posturas', to='core.candidato')),
                ('opcion_respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posturas_asociadas', to='core.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posturas_candidatos', to='core.pregunta')),
            ],
            options={
                'verbose_name_plural': 'Posturas de Candidatos',
                'unique_together': {('candidato', 'pregunta')},
            },
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_respuesta', to='core.pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tipo_eleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='core.tipoeleccion'),
        ),
        migrations.CreateModel(
            name='DecisionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_decision', models.DateTimeField(auto_now_add=True)),
                ('candidato_elegido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elegido_por_usuarios', to='core.candidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisiones_finales', to=settings.AUTH_USER_MODEL)),
                ('tipo_eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoeleccion')),
            ],
            options={
                'verbose_name_plural': 'Decisiones Finales',
                'unique_together': {('user', 'tipo_eleccion')},
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipos_eleccion',
            field=models.ManyToManyField(related_name='candidatos', to='core.tipoeleccion'),
        ),
        migrations.DeleteModel(
            name='Apoyo',
        ),
        migrations.DeleteModel(
            name='Cualidad',
        ),
        migrations.DeleteModel(
            name='InteresPolitico',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AlterUniqueTogether(
            name='opcionrespuesta',
            unique_together={('pregunta', 'valor')},
        ),
    ]
