# Generated by Django 5.2.1 on 2025-06-04 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_respuestausuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='opcionrespuesta',
            unique_together={('pregunta', 'texto')},
        ),
    ]
