# Generated by Django 5.2.1 on 2025-06-04 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_opcionrespuesta_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCandidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('num_preguntas_consideradas', models.IntegerField(default=0)),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.candidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_candidato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Matches de Candidatos',
                'unique_together': {('user', 'candidato')},
            },
        ),
    ]
