# Generated by Django 5.2.1 on 2025-06-06 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_matchcandidato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturacandidato',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posturas_candidato', to='core.candidato'),
        ),
        migrations.AlterField(
            model_name='posturacandidato',
            name='opcion_respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.opcionrespuesta'),
        ),
        migrations.AlterField(
            model_name='posturacandidato',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pregunta'),
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('hora_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Noticias',
                'unique_together': {('titulo', 'descripcion')},
            },
        ),
    ]
