# Generated by Django 5.2.1 on 2025-06-06 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_posturacandidato_candidato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name_plural': 'Noticias'},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='hora_subida',
            new_name='fecha_publicacion',
        ),
    ]
