# Generated by Django 5.2.1 on 2025-06-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
