# Generated by Django 5.2.16 on 2026-07-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_profile_picture_and_drop_noticia_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchcandidato',
            name='breakdown_por_eje',
            field=models.JSONField(blank=True, default=dict, help_text="Dict eje -> {'porcentaje': X, 'preguntas': N}. Para radar chart en el frontend."),
        ),
        migrations.AddField(
            model_name='matchcandidato',
            name='confianza',
            field=models.CharField(choices=[('tentativa', 'Tentativa (pocos datos)'), ('media', 'Confianza media'), ('alta', 'Confianza alta')], default='tentativa', max_length=15),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='es_no_se',
            field=models.BooleanField(default=False, help_text="Si es True, esta opcion representa 'No se / Prefiero no responder' y se excluye del calculo de match."),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='eje_tematico',
            field=models.CharField(choices=[('ECONOMIA', 'Economia'), ('SOCIEDAD', 'Sociedad'), ('AMBIENTE', 'Ambiente'), ('SEGURIDAD', 'Seguridad'), ('DDHH', 'Derechos Humanos'), ('INTERNACIONAL', 'Politica Internacional'), ('INSTITUCIONAL', 'Reforma Institucional'), ('OTRO', 'Otro')], default='OTRO', help_text='Categoria tematica de la pregunta. Sirve para el match por eje.', max_length=20),
        ),
        migrations.AddField(
            model_name='respuestausuario',
            name='peso',
            field=models.IntegerField(choices=[(0, 'No me importa'), (1, 'Poco importante'), (2, 'Importante'), (3, 'Muy importante')], default=1, help_text='Cuanto le importa al usuario este tema. Multiplica el peso de la pregunta en el match.'),
        ),
    ]
