# Generated by Django 5.2.16 on 2026-07-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_algoritmo_robusto'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='candidatos_mencionados',
            field=models.ManyToManyField(blank=True, help_text='Candidatos referenciados por esta noticia.', related_name='noticias', to='core.candidato'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='fuente',
            field=models.CharField(blank=True, default='', help_text="Medio de origen: 'Google News', 'La Tercera', 'Emol', etc.", max_length=200),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen_url',
            field=models.URLField(blank=True, default='', help_text='URL del thumbnail (opcional).', max_length=1000),
        ),
        migrations.AddField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True, default='', help_text='Link al articulo original. Se usa como clave logica para dedup.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
        migrations.AddConstraint(
            model_name='noticia',
            constraint=models.UniqueConstraint(condition=models.Q(('url', ''), _negated=True), fields=('url',), name='noticia_url_unique_when_not_empty'),
        ),
    ]
