# Generated by Django 5.2.16 on 2026-07-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_noticia_extendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='explicacion',
            field=models.TextField(blank=True, default='', help_text='Contexto educativo neutro sobre que trata la pregunta (2-3 lineas).'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='repercusiones',
            field=models.JSONField(blank=True, default=dict, help_text='Dict con keys: economico, social, cultural, ambiental, institucional. Cada valor es un texto breve explicando el impacto en esa dimension.'),
        ),
    ]
