# Generated by Django 5.2.16 on 2026-07-26 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Noticias guardadas',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('user', 'noticia')},
            },
        ),
        migrations.CreateModel(
            name='PosturaBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('postura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.posturacandidato')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posturas_bookmark', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Posturas guardadas',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('user', 'postura')},
            },
        ),
    ]
