# Generated by Django 5.2.16 on 2026-07-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_noticiabookmark_posturabookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoeleccion',
            name='es_base',
            field=models.BooleanField(default=False, help_text='Si es True, las preguntas de este tipo se agregan a TODAS las elecciones. Usado para preguntas transversales de valores/ideologia que se responden una sola vez.'),
        ),
    ]
