# Generated by Django 5.2.16 on 2026-07-26 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_tipoeleccion_es_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_romano', models.CharField(help_text="I, II, III... o 'RM' para Region Metropolitana.", max_length=5, unique=True)),
                ('codigo', models.CharField(help_text="Codigo oficial INE de 2 digitos (ej. '01', '13').", max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('nombre_corto', models.CharField(blank=True, default='', help_text="Abreviatura para UI (ej. 'AyP', 'RM', 'BioBio').", max_length=20)),
                ('orden', models.IntegerField(default=0, help_text='Orden geografico norte-sur para presentacion en UI.')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(help_text='Numero oficial del distrito (1 al 28).', unique=True)),
                ('nombre', models.CharField(help_text="Nombre descriptivo (ej. 'Distrito 10 - Santiago Centro').", max_length=100)),
                ('escanos', models.IntegerField(default=0, help_text='Cantidad de diputados que elige este distrito.')),
                ('region', models.ForeignKey(help_text='Region a la que pertenece. Un distrito no cruza regiones.', on_delete=django.db.models.deletion.PROTECT, related_name='distritos', to='core.region')),
            ],
            options={
                'verbose_name': 'Distrito electoral',
                'verbose_name_plural': 'Distritos electorales',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Codigo oficial de comuna (5 digitos SUBDERE).', max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('distrito', models.ForeignKey(help_text='Distrito electoral al que pertenece la comuna.', on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='core.distrito')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comunas', to='core.region')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['region__orden', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('nombre', 'region'), name='unique_comuna_por_region')],
            },
        ),
    ]
