# Generated by Django 5.2.16 on 2026-07-26 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_region_distrito_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='comuna',
            field=models.ForeignKey(blank=True, help_text='Comuna en la que compite (alcaldes/concejales). Null si es nacional o distrital.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='core.comuna'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='distrito',
            field=models.ForeignKey(blank=True, help_text='Distrito en el que compite (diputados). Null si es nacional o comunal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='core.distrito'),
        ),
    ]
