# Generated by Django 5.2.16 on 2026-07-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_candidato_comuna_candidato_distrito'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.CheckConstraint(condition=models.Q(('comuna__isnull', False), ('distrito__isnull', False), _negated=True), name='candidato_no_comuna_y_distrito_a_la_vez'),
        ),
    ]
