# Generated by Django 5.2.16 on 2026-07-26 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_candidato_candidato_no_comuna_y_distrito_a_la_vez'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comuna', models.ForeignKey(blank=True, help_text='Comuna en la que vota el usuario. Determina que alcaldes y diputados le corresponden en el matching.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votantes', to='core.comuna')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
    ]
