# Generated by Django 5.2.16 on 2026-07-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_backfill_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoeleccion',
            name='anio',
            field=models.IntegerField(blank=True, help_text='Ano electoral (ej. 2021, 2025). Permite tener multiples versiones del mismo tipo (Presidencial 2021 vs Presidencial 2025) y filtrar.', null=True),
        ),
    ]
