# Generated by Django 5.2.16 on 2026-07-26 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_backfill_anios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Slug canonico. Ej: 'ECONOMIA', 'SALUD'. Se compara case-insensitive.", max_length=32, unique=True)),
                ('nombre', models.CharField(help_text="Nombre para mostrar. Ej: 'Economia', 'Salud'.", max_length=64)),
                ('color', models.CharField(default='#666666', help_text="Color hex para el radar chart y badges. Ej: '#FFC220'.", max_length=7)),
                ('icono', models.CharField(blank=True, default='', help_text='Nombre de icono (Ionicons/Lucide). Opcional.', max_length=32)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparicion en el radar/UI.')),
                ('activo', models.BooleanField(default=True, help_text='Si esta desactivado, el eje sigue en DB pero no se muestra al usuario.')),
                ('descripcion', models.TextField(blank=True, default='', help_text='Descripcion educativa del eje. Se muestra en tooltips.')),
            ],
            options={
                'verbose_name': 'Eje tematico',
                'verbose_name_plural': 'Ejes tematicos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='eje',
            field=models.ForeignKey(blank=True, help_text='Referencia al catalogo Eje. Se sincroniza automaticamente con eje_tematico. Setealo aca si querés override o dejalo vacio y el signal lo resuelve por codigo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preguntas', to='core.eje'),
        ),
    ]
