# Generated by Django 5.2.16 on 2026-07-26 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_seed_ejes_canonicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadTerritorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text="Codigo canonico. Ej: 'NACIONAL', 'REG-13', 'D-10', 'COM-13120'.", max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=128)),
                ('nivel', models.CharField(choices=[('nacional', 'Nacional'), ('regional', 'Regional'), ('provincial', 'Provincial'), ('distrital', 'Distrital'), ('comunal', 'Comunal')], max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Data extra: 'poblacion', 'codigo_ine', 'circunscripcion_senatorial', etc.")),
                ('padre', models.ForeignKey(blank=True, help_text='Unidad de nivel superior. Ej: comuna -> distrito, distrito -> region.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='core.unidadterritorial')),
            ],
            options={
                'verbose_name': 'Unidad territorial',
                'verbose_name_plural': 'Unidades territoriales',
                'ordering': ['nivel', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='unidad_territorial',
            field=models.ForeignKey(blank=True, help_text='Unidad territorial polimorfica. Permite escalar a senadores (regional), CORE (provincial), etc. sin agregar FKs nuevos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidatos', to='core.unidadterritorial'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unidad_territorial',
            field=models.ForeignKey(blank=True, help_text='Unidad territorial polimorfica del votante. Permite matchear contra candidatos de cualquier nivel (nacional/regional/distrital/comunal) via jerarquia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votantes', to='core.unidadterritorial'),
        ),
        migrations.AddIndex(
            model_name='unidadterritorial',
            index=models.Index(fields=['nivel'], name='core_unidad_nivel_2dca8c_idx'),
        ),
        migrations.AddIndex(
            model_name='unidadterritorial',
            index=models.Index(fields=['padre'], name='core_unidad_padre_i_5afd26_idx'),
        ),
    ]
