# Generated by Django 5.2.16 on 2026-07-27 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_delete_decisionfinal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='candidato',
            name='candidato_no_comuna_y_distrito_a_la_vez',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='distrito',
        ),
    ]
