# Generated by Django 5.2.16 on 2026-07-31 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_drop_candidato_comuna_distrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='eje_tematico',
            field=models.CharField(choices=[('ECONOMIA', 'Economia'), ('SOCIEDAD', 'Sociedad'), ('AMBIENTE', 'Ambiente'), ('SEGURIDAD', 'Seguridad'), ('DDHH', 'Derechos Humanos'), ('INTERNACIONAL', 'Politica Internacional'), ('INSTITUCIONAL', 'Reforma Institucional'), ('OTRO', 'Otro'), ('PUEBLOS_ORIGINARIOS', 'Pueblos Originarios'), ('DISCAPACIDAD', 'Discapacidad')], default='OTRO', help_text='Categoria tematica de la pregunta. Sirve para el match por eje.', max_length=24),
        ),
    ]
