# Generated by Django 5.2.16 on 2026-08-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_ejes_obsoletos'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='lista_electoral',
            field=models.CharField(blank=True, default='', help_text="Pacto o lista electoral a la que pertenece el candidato (ej. 'C. Unidad por Chile').", max_length=200),
        ),
    ]
