# Generated by Django 5.2.16 on 2026-08-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_add_lista_electoral_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='curriculum_url',
            field=models.URLField(blank=True, default='', help_text='URL al curriculum oficial en senado.cl o camara.cl.'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email de contacto oficial.', max_length=254),
        ),
        migrations.AddField(
            model_name='candidato',
            name='fono',
            field=models.CharField(blank=True, default='', help_text='Teléfono de contacto oficial.', max_length=50),
        ),
        migrations.AddField(
            model_name='candidato',
            name='parlid',
            field=models.CharField(blank=True, default='', help_text='ID oficial del parlamentario en el sistema del Senado/Camara.', max_length=20),
        ),
    ]
