# Generated by Django 5.2.17 on 2026-09-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_add_parlid_email_curriculum_fono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Foto de perfil del candidato. Nulo = sin foto (el frontend muestra iniciales).', null=True, upload_to='profiles/'),
        ),
    ]
